Feat: updated template to Lumen
BuildForSDG/Phenom-Backend pull request #6
Opened 2020-05-16 11:39 UTC by onyijne

BREAKING CHANGES: changed App namespace from app directory to src directory

## Description
After pulling to your local machine run `composer install` to install dependencies.

Fixes #2 

## How Has This Been Tested?
I used php inbuilt server to test run it.

## Screenshots (if applicable, else remove this line / section)

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

2020-05-19 05:19 UTC, uchennaibekwe commented on composer.json
> +    "name": "Phenom-Backend",
I got the error: 

> Deprecation warning: Your package name phenom-backend is invalid, it should have a vendor name, a forward slash, and a package name ...  Make sure you fix this as Composer 2.0 will error.

Changing it to "_phenom/backend_" (all lower case) fixes that.

2020-05-19 05:23 UTC, uchennaibekwe requested changes
This is done well!
I have left a comment that should consider addressing before this gets merged.

2020-05-19 14:00 UTC, uchennaibekwe approved these changes

2020-05-21 05:55 UTC, AliyuAhmad approved these changes
Looks good

2020-05-21 09:15 UTC, uchennaibekwe approved these changes

2020-05-21 09:26 UTC, maryabik approved these changes

2020-05-21 15:19 UTC, merged